version: '3'
services:
  mysql:
    container_name: mysql8
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      wonknet:
        ipv4_address: 172.18.0.6
    volumes: 
      - ./docker-volume/mysql:/var/lib/mysql
      - ./docker-volume/my.cnf:/etc/mysql/my.cnf
    # volumes:
    #   - type: volume
    #     source: mysql
    #     target: /var/lib/mysql
    #     read_only: false
networks:
  wonknet:
    name: wonknet
    external: true
    
# volumes:
#   mysql: